### ISSUE TITLE
Build and push docker images of runtime to public docker hub

### ISSUE THREAD

**Issue by ntabris** [coiled/coiled-runtime#142]
Currently the runtime/default Coiled software environments are built by Coiled from the conda env file. The result is that Coiled builds a docker image which is stored in our public ECR registry.

We (platform) would like it if your CI instead built a docker image and pushed this to docker hub, then created the Coiled software environment from that (using `--container` arg instead of `--conda`).

If the default software environments are pulled from docker hub, then we don't have expense of egress on our public ECR registry. Rate limiting *shouldn't* be a problem because each node pulling image would have different IP address.

(Less important but this also makes local dev easier because we could much more quickly create software env from public images in docker hub. Some of us are already building our own images and pushing to docker hub to do this, but it seems like this might as well be done automatically for runtime using CI.)

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @ntabris. Switching to a pure `container` software environment seems reasonable given the reasons you outlined. I think this might also give us the flexibility to use `mamba` instead of `conda` (since I believe Coiled still uses `conda` -- though I could be wrong about that) which will probably help speed things up. @marcosmoyano I know you recently updated the CI for automatic software environment creation over in https://github.com/coiled/coiled-runtime/pull/128. Do you have bandwidth / interest in working on this issue too? Might be a good opportunity for our teams to collaborate 

> Rate limiting _shouldn't_ be a problem because each node pulling image would have different IP address

I'm not familiar with docker hub's rate limiting. Is this something we're confident about, or should try to test beforehand?

**Comment by ncclementi** [comment]
I'd be interested in learning more about docker, I played with it in the past but nothing too serious. @marcosmoyano if you know how to go about this, have the bandwidth, and want to pair, I'd be happy to join efforts. 🇦🇷 🚀

**Comment by ntabris** [comment]
> I'm not familiar with docker hub's rate limiting. Is this something we're confident about, or should try to test beforehand?

The rate limiting is 100 pulls per 6 hours **per IP address**, so I'm fairly confident we're fine as far as pulls from the cluster. (Ref: https://docs.docker.com/docker-hub/download-rate-limit/)

We may need to adjust platform code that does a check on image, since these checks would all come from our control plane (so more or less a single IP address).

Probably not worth it but I wonder how much work it would be to qualify as OSS project so there wouldn't be limit: https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

**Comment by ntabris** [comment]
I suspect you'd want to use https://github.com/marketplace/actions/build-and-push-docker-images to build and push docker image in CI.

**Comment by jrbourbeau** [comment]
> The rate limiting is 100 pulls per 6 hours per IP address, so I'm fairly confident we're fine as far as pulls from the cluster. (Ref: https://docs.docker.com/docker-hub/download-rate-limit/)

Just confirming -- this is because each worker / scheduler node gets their own unique IP address and only needs to pull the software environment image once (when starting up)? 

> We may need to adjust platform code that does a check on image, since these checks would all come from our control plane (so more or less a single IP address).

Is this something we should wait to be done before moving the default software environments over to being `container`-based? 

> 🇦🇷 🚀

Woo!

**Comment by marcosmoyano** [comment]
@ncclementi Sorry I was out all day yesterday. I'm not **super** familiar with Docker but this could be a good opportunity to get to know it a bit better 😄  🇦🇷 🚀

**Comment by ncclementi** [comment]
@ntabris I see that there is also an option to publish the image to Github container registry. Is this something we support or we would be interested in? 
I wonder if we can get away with the free version, https://github.com/pricing according to the table at the end of this blog, there are no pull costs, https://cloudonaut.io/amazon-ecr-vs-docker-hub-vs-github-container-registry/

**Comment by ntabris** [comment]
Haven't dug in but I'd think Github isn't targeting our use-case as much. The linked page says

> anyone who wants to download your container image needs to authenticate with a GitHub user account

which would be a little annoying.
