### ISSUE TITLE
Publish nightly Coiled software environments

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#147]
In https://github.com/coiled/coiled-runtime/pull/128 we automated creating Coiled software environment for released versions of `coiled-runtime` on staging.coiledhq.com. As a follow-up we should also update our software environment CI to create a nightly Coiled software environment that uses the `coiled-runtime` nightly build. This will increase the chance that we catch regressions/bugs/etc early.

**Comment by ncclementi** [comment]
Few comments/questions regarding this issue.

- Do we want these environments to be in the coiled account or should we just aim for docker hub? 
We will be only using this for testing on staging, is my understanding. I wonder if there is a preference on how to approach this. @shughes-uk @marcosmoyano Do you have a preference?

- If we choose docker hub I'll go for adding the necessary steps in the pre-release workflow as it runs every night. Does this seem reasonable @jrbourbeau? Otherwise, we should probably do a separate job, as the software environment one only runs on main when the `environments/` folder is modified.

**Comment by jrbourbeau** [comment]
> Do we want these environments to be in the coiled account or should we just aim for docker hub?

Sorry, I don't quite follow here. I thought we would treat the nightly `coiled-runtime` software environment similarly to other Coiled software environments. That is, after https://github.com/coiled/coiled-runtime/pull/154 is merged, each runtime Coiled software environment is a container-only software env. Does that help address your question, or am I missing something? 

> If we choose docker hub I'll go for adding the necessary steps in the pre-release workflow as it runs every night. Does this seem reasonable @jrbourbeau? Otherwise, we should probably do a separate job, as the software environment one only runs on main when the environments/ folder is modified.

I have the sense that keeping all the logic around creating docker images in the same workflow will help minimize complexity. We should be able to update the existing software environment GHA workflow to also run on a scheduled cron job for the nightly software environment

**Comment by marcosmoyano** [comment]
> coiled env create --name coiled/$COILED_SOFTWARE_ENV_NAME --conda environments/$COILED_SOFTWARE_ENV_NAME.yml

Right, we would create them with `--container` instead of `--conda`
