### ISSUE TITLE
Determine where historical benchmarking data should live 

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#187]
As part of https://github.com/coiled/coiled-runtime/issues/148, we'll need to store historical benchmark results somewhere. We should determine where those results should live. For example:

- In this repository
- In a dedicated `coiled-runtime-benchmarks` (or some other name) repository
- In S3
- ...

Related to https://github.com/coiled/coiled-runtime/issues/186

**Comment by ian-r-rose** [comment]
A quick update on my thinking here:

In #208 we are keeping historical data (as well as cluster dumps and probably performance reports) as a sqlite file in S3. This is an easy decision to reverse if we want to try to do something else, since it's a fairly straightforward tabular dataset written using sqlalchemy, all of which is pretty swappable.

We had a couple of discussions around keeping the benchmarks checked into the repo. This may work, and we can revisit this, but I think we want to avoid that for the time being in order to keep flexibility while we explore different models of running CI. This avoids having to work through merge conflicts with concurrent builds, having benchmark updates trigger their own CI runs, etc (none of those are insurmountable, but are not necessary right now, IMO).
