### ISSUE TITLE
Benchmarking tracking - missing data/updates

### ISSUE THREAD

**Issue by ncclementi** [coiled/coiled-runtime#217]
I was going over the benchmark pages in https://coiled.github.io/coiled-runtime/index.html and I noticed that we have some missing updates and some tabs completely missing or that we are not tracking. I'm not sure what are we supposed to expect. 

Notes: 

Fully updated pages (Stability, Benchmark and Runtime tabs): upstream-py3.9, latest-py3.9 0.0.4-py3.9 and 0.0.3-py3.9

The folder tests/benchmarks and test/runtime run only on this matrix, which makes sense: https://github.com/coiled/coiled-runtime/blob/fb3a04f91581c2582c520b30006f63cd0055f156/.github/workflows/tests.yml#L114-L117

However, the latest-py3.9 page seems to have a problem, because it stopped being updated on Sat 23rd
https://coiled.github.io/coiled-runtime/coiled-latest-py3.9.html

All the remaining cases have only  Stability tabs, probably because we have a bigger matrix for Stability but they stopped updating on what looks Sat 23rd but I can't find what happened. @ian-r-rose thoughts?

**Comment by ian-r-rose** [comment]
Thanks for the write-up @ncclementi.

> . I'm not sure what are we supposed to expect.

You basically got it right -- we should expect a separate page for each of the items in the matrix. So if `Stability` has a larger matrix, it will appear on more of the pages. I'm looking into why some seem short right now.

**Comment by ian-r-rose** [comment]
Update -- we are seeing less data in the "latest" CI runs because those are actually not run on the schedule. We are currently running 0.0.3, 0.0.4, and "upstream" in the scheduled job, as determined by the matrix and the `$TEST_UPSTREAM` variable.

So I'd say this is performing as expected. Now, we may want to change the cadence and matrix coverage of our test suite (I personally think the current setup is a bit too complicated). But I think this issue can be closed in favor of a larger discussion of how to structure the test matrix.

**Comment by ncclementi** [comment]
Since things are working as expected I'm closing this issue and leaving the CI matrix simplification to discuss separately.
