### ISSUE TITLE
Following test instructions doesn't work on a fresh environment

### ISSUE THREAD

**Issue by gjoseph92** [coiled/coiled-runtime#227]
Following the test instructions in https://github.com/coiled/coiled-runtime/blob/b827b15e7ca40856e34ba624a116cd4384a09be0/README.md#test gives
```bash
(coiled-runtime) gabe dev/coiled-runtime ‹main› » python -m pytest tests                                                                                                    4 ↵
ImportError while loading conftest '/Users/gabe/dev/coiled-runtime/conftest.py'.
conftest.py:15: in <module>
    import dask
E   ModuleNotFoundError: No module named 'dask'
```
because `environment.yml` doesn't contain the Coiled runtime itself. The instructions probably need to include installing the coiled runtime as well.

Or are you supposed to run `python ci/create_latest_runtime_meta.py` and then `mamba env update -f latest.yaml`?

**Comment by jrbourbeau** [comment]
Ah, thank @gjoseph92, you're totally right that `coiled-runtime` itself needs to be installed. 

> Or are you supposed to run python ci/create_latest_runtime_meta.py and then mamba env update -f latest.yaml?

Seems sensible to me. That's what we're doing in CI. FWIW if there was a way to point `mamba env update` directly to a conda recipe `meta.yaml` file, that would also work and might be a bit more of a streamlined process. I wasn't aware of such a way to do that, which is why we have the `ci/create_latest_runtime_meta.py` script

**Comment by gjoseph92** [comment]
To follow up, even after doing this, I still wasn't able to run integration tests, because `coiled-runtime` itself wasn't installed, so the test suite couldn't figure out which software environment to use.

I'm a strong believer in package_sync and would prefer to just get https://github.com/coiled/coiled-runtime/pull/235 to work. Updating the docs would be good, but the developer experience would be even nicer that way :)

**Comment by ncclementi** [comment]
Closing this as package sync is now the standard.
