### ISSUE TITLE
Avoid version mismatch warning

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#75]
When users connect their client to a cluster, a warning is emitted if there is a version mismatch found for any of [these packages](https://github.com/dask/distributed/blob/7a564663bfda4949e5cc088a7cd66511e2d85e3f/distributed/versions.py#L15-L28) on any node throughout the cluster. We should ensure that if a specific version of `coiled-runtime` is used, that we never emit a version mismatch warning. 

Today we pin some of the relevant packages

https://github.com/coiled/coiled-runtime/blob/0667395184944e17968a1211672de3e8b24c497a/recipe/meta.yaml#L21-L44

like `dask`, `distributed`, `numpy`, `lz4`, etc. but not all (e.g. `cloudpickle`, `tornado`, etc). This means that, for example, if someone installs `coiled-runtime=0.0.3` locally today and then tomorrow a new `cloudpickle` release comes out, a version mismatch warning will be emitted when that local environment connects to a fresh Coiled cluster using a `coiled-runtime=0.0.3`-based software environment. 

I suggest we pin all packages in `coiled-runtime` which can lead to a Dask version mismatch warning. Though thoughts from others are certainly welcome.

**Comment by ntabris** [comment]
I don't full understand the proposal, and I'm going to ask some questions that show I don't know much about this. Hope you don't mind.

Sometimes things blow up if you have different versions of something on client/scheduler/worker. Is that only true for a well-defined set of packages, so that version mismatches for other packages are fine? Or could any package X (in principle) cause bad things if you have version mismatch? If in principle anything could be a problem, then is the proposal to pin everything in the dependency tree?

Would we monitor everything pinned/everything in the dependency tree and release a new version of `coiled-runtime` to bump pins whenever there's a security patch (non-trivial bug fix?) in a dependency? (Not sure how often things in our dependencies have security patches since I'm not a full-time resident of this part of the python ecosystem, but this sounds like a non-trivial responsibility.) If so, would we recommend that customers not pin to patch version of `coiled-runtime` (and we'd do sufficient testing to be moderately confident that patch updates won't break stuff)?

**Comment by jrbourbeau** [comment]
> Is that only true for a well-defined set of packages, so that version mismatches for other packages are fine? Or could any package X (in principle) cause bad things if you have version mismatch?

Any package version mismatch could lead to things failing. Distributed will check a few libraries (e.g. Python, `dask`, `distributed`, etc.) that are common offenders for causing things to fail and emit a warning is one of those packages has a version mismatch. That doesn't mean things can't go wrong due to other packages, but does help in lots of common cases.

> If in principle anything could be a problem, then is the proposal to pin everything in the dependency tree?

I'm just proposing we pin the specific packages `distributed` checks by default (which I think are all dependencies of `distributed`) to make sure `coiled-runtime` users don't get a red warning message 

> Would we monitor everything pinned/everything in the dependency tree and release a new version of coiled-runtime to bump pins whenever there's a security patch (non-trivial bug fix?) in a dependency?

I'm not too concerned about security patches here. For this part of the Python stack they have been historically very rare. We're still determining our version scheme and can factor this point in when making a final decision 

> This would mean that, for the life of any supported coiled-runtime release, coiled will be constrained by that dependency.

Fair point, I'll have to look at the `coiled` dependencies to get a sense for how much of an issue this may be
