### ISSUE TITLE
Strategies for evaluating cluster stability during stability tests

### ISSUE THREAD

**Issue by sjperkins** [coiled/coiled-runtime#92]
In https://github.com/coiled/coiled-runtime/pull/84, the following strategy was applied for checking whether workers had deadlocked during computation

```python
    fs = client.compute((ddf.x + ddf.y).mean())
    INTERVAL = 5
    start = time()

    while fs.status == "pending" and time() - start < 2 * 60:
        # We'd like to have seen all workers in the last INTERVAL seconds
        workers = list(client.scheduler_info()["workers"].values())
        assert all(time() - w["last_seen"]  < INTERVAL for w in workers)
        sleep(INTERVAL)

    wait(fs, timeout=0.1)   # Reify success or error
```

Alternative strategies might include:

- Checking the distribution of worker heartbeats
- Within a SchedulerPlugin for instance
- It's probably worth doing a cluster dump if the test fails and producing this as a test artefact.

/cc @mrocklin, @fjetter, @jrbourbeau, @gjoseph92 if you have further ideas.

**Comment by ncclementi** [comment]
@fjetter is this still a relevant issue, or what we have here https://github.com/coiled/coiled-runtime/blob/main/tests/stability/test_deadlock.py is a replacement of the code in the comment above?

**Comment by fjetter** [comment]
I think this issue is rather about "collect more information during our test run to infer if something went wrong". I think this is still relevant but there is also nothing actionable here, yet. I would suggest to hold off on this until we have a better idea of what we're looking for.

Since there hasn't been any activity since creation, I'll close the issue. We can reopen it again once it becomes relevant
